basic:
  # 出战队伍的编号, 从0开始计数
  team_id: 4

  # 目标悬赏的编号, 从0开始计数
  boss_id: 2
  # 队伍中佣兵的数量，至少3人
  hero_count: 6
  # 完成悬赏后的奖励数目
  reward_count: 5
  # 在拿到神秘选项后是否提前结束战斗, 1 为提前结束, 0 为继续战斗
  early_stop: 0
  # 连续操作之间的延迟, 如果脚本经常少点某些按钮, 你可能需要增加延迟使delay > 1.0
  delay: 0.5
  # 屏幕上图像模板匹配的置信阈值
  confidence: 0.8
  # 战斗中佣兵的排序, 从0开始计数



  # PVP投降脚本 或者 PVE
  mode: 'pve' # 'pvp' or 'pve'
  # 投降延迟时间
  pvp_delay: 0.5 # in seconds
  # 是否快速投降，因为官方的设置，有时候投降按钮位置会变化，快速投降会导致投降失败，
  fast_surrender: 0 # 1为快速投降，0为识别投降按钮再投降，当然投降速度会变慢
  # 如果界面卡住，最多等多久重启炉石
  longest_waiting: 80 # 秒计
  # 战网路径(注意路径要加双斜杠)
  bn_path: 'C:\\Program Files (x86)\\Battle.net\\Battle.net.exe'
  # 遇到，掉线等是否自动重启
  auto_restart: 0 # 1为自动重启，0为否



retry:
  # 最大重试技能次数，达到次数后如果依然不成功，认输
  skill_selection: 6
  # 最大重试选择英雄从手牌中打出的次数，达到次数后如果依然不成功，认输
  hero_selection: 6
  # 最大重试找到地图上下一个房间的次数，达到后如果依然不成功，提前结束副本
  map_ready: 10

# coordinations of buttons etc.
location:
  # hero battle field locations
  heros: [ 677, 807, 943, 641 ] #  [first_x, mid_x, last_x, y]
  # hero skills locations
  skills: [ 653, 801, 963, 450 ] # [first_x, mid_x, last_x, y]
  skill_waiting: [100, 60]
  # enemy battle field locations
  enemies: [ 677, 850, 943, 285 ] # [first_x, mid_x, last_x, y]

  # boss list locations
  boss: [ 405, 696, 916, 350, 667 ] # [first_x, mid_x, last_x, upper_y, lower_y]

  # treasures locations
  treasures: [ 707, 960, 1200, 376 ] # [first_x, mid_x, last_x, y]
  # treasure collection button
  treasures_collect: [ 968, 765 ] # [x, y]

  # visitors locations
  visitors: [ 545, 790, 1042, 420 ] # [first_x, mid_x, last_x, y]
  # visitor confirm button
  visitors_confirm: [ 791, 688 ] # [x, y]

  # heros on hand locations
  members: [ 622, 1000, 900 ] # [first_x, last_x, y]
  members_distance: 110
  # drag on hand hero to this location
  dragto: [ 1213, 564 ] # [x, y]

  # focus area before battle
  focus: [ 420, 650, 900, 453 ] # [first_x, mid_x, last_x, y]

  # final boss reward locations, depending on rewards count
  rewards:
    5: "(608, 706), (1034, 720), (1117, 371), (846, 311), (541, 430)" # [(x1, y1), ... ]
    4: "(660, 314), (554, 687), (1010, 794), (1117, 405)" # [(x1, y1), ... ]
    3: "(608, 706), (1034, 720), (1117, 371), (846, 311), (541, 430)" # [(x1, y1), ... ]
    # confirm button after reward collection
    confirm: [ 806, 525 ] #[x, y]

  # last boss location on map
  final_boss: [ 646, 227 ]
  # last confirm after finishing the map
  final_confirm: [ 794, 779 ]

  # empty location to click when waiting
  empty: [ 1488, 921 ]
  # empty location to click when waiting during battles
  empty_battle: [ 620, 750 ]
  # mouse location during scroll
  scroll: [ 1011, 764 ]
  # travel point confirm button
  travel: [ 1090, 674 ] #[x, y]
  # start point campfire on the map
  start_point: [ 646, 712 ] # [x, y]

  # team locations
  teams: [ 390, 600, 820, 330, 450, 600 ] # [first_x, mid_x, last_x, first_y, mid_y, last_y]
  # team select confirm button
  team_select: [ 1190, 800 ] # [x, y]
  # team lock button
  team_lock: [ 704, 572 ]

  # start game button, on boss selected or path selected
  start_game: [ 1250, 732 ] # [x, y]
  # start battle button, on skill selection finished
  start_battle: [ 1327, 454 ] # [x, y]

  # option button
  options: [ 1580, 920 ] # [x, y]
  # surrender button
  surrender: [ 815, 350 ] # [x, y]
  # view team members button
  view_team: [ 647, 885 ]
  # give up button
  give_up: [ 929, 706 ]
  # give up confirm button
  give_up_cfm: [ 712, 560 ]
  pvp_reward: [ 804, 471 ]

  # Region of cards on Battlefield
  enemy_region: [ 400, 293, 1230, 393 ] # [x1, y1, x2, y2]
  hero_region: [ 400, 650, 1230, 750 ]
  hero_nready_region: [400, 580, 1230, 680]

cv:
  hero_center_y_offset: 70
  hero_image_size: [50, 35]

  color_thresh: 250
  hero_color_thresh: 100
  color_y_offset: 28
  color_region_offset: [5, 10]

  digit_size: [17, 30]
  digit_conf: 0.7
  digit_template_w: 28

  # game resolution
  resolution: [1600, 900]
