auto_restart: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net Launcher.exe
boss_id: 4
early_stop: false
hero:
  BARL_009H:
  - "指挥官沃恩"
  - War Master Voone
  - "3,2,1"
  - 5
  LETL_028H:
  - "拉格纳罗斯"
  - Ragnaros
  - "2,3,1"
  - 0
  LETL_030H:
  - "迦顿男爵"
  - Baron Geddon
  - "2,3,1"
  - 1
  LETL_031H:
  - "阿莱克丝塔萨"
  - Alexstrasza
  - "3,2,1"
  - 4
  SWL_01H:
  - "安东尼达斯"
  - Antonidas
  - "2,1,3"
  - 2
  SWL_26H:
  - "迪亚波罗"
  - Diablo
  - "3,2,1"
  - 3
hs_path: E:/Games/Hearthstone/Hearthstone.exe
lang: ZH-1600x900
reward_count: 5
team_id: 3
